### PR TITLE
Fixes auth refresh token issue

### PR DESCRIPTION
**Pull request by dhmi19**
## Notion ticket link

[Doesn’t force logout upon token expiry?](https://www.notion.so/uwblueprintexecs/Doesn-t-force-logout-upon-token-expiry-e4a42d1e4f234e81b951eaaf1342ade2)

## Implementation description
* Fixes an issue with the refresh token not being set in local storage upon refresh

## Steps to test
1. Try making a request with an expired token
2. Retry making the request. Your token should be valid now and the request should work

## What should reviewers focus on?
* Just test the change to make sure it works as expected- thanks!

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have run docker-compose up and my project compiled
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Comment by susheelk** [comment]
Steps to Test:
* Login as normal
* Go into local storage and invalidate your access token (add/remove a char, etc)
* Refresh the page, API requests should go through, you should get a fresh token

**Comment by susheelk** [comment]
Does this work for you? I'm getting a `401` on every request. (I tried just loading the admin dashboard). It works on `development` tho

**Comment by hyunzeekim** [comment]
I'm also getting a `401` on request like Susheel.

**Review by obaranek — APPROVED** [review]

**Review by susheelk — APPROVED** [review]
Tested with a stale auth token + valid refresh token:
* With code on development, getting a `401`
* With code in this branch, fresh token is issued and request goes through
:heavy_check_mark:

**Pull request merged**
