### PR TITLE
Create Admin Dashboard

### PR DESCRIPTION
**Pull request by hyunzeekim**
## Notion ticket link

[Admin Dashboard Table](https://www.notion.so/uwblueprintexecs/Admin-Dashboard-Table-8f1a246ab43d4dd58da99265add637fa)

## Implementation description
* Added mui datatable
* Created Admin Dashboard component
* Created Author component for displaying tooltip based on overflow
* Mock data included for now
admin dashboard table

## Steps to test
1. Modify mock data table as necessary

## What should reviewers focus on?
* Correct code
* Making sure everything works :)

## Checklist
- [X] My PR name is descriptive and in imperative tense
- [X] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have run docker-compose up and my project compiled
- [X] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by Tahmeed27 — APPROVED** [review]
Looks greattt!

**Review by chriistine — APPROVED** [review]
LGTM - just 1 question: I don't think this was in the design that was linked on the notion ticket so might be out of scope for this ticket but @Tahmeed27 do you know if this is how we wanted to present the tags? 
image
thinking it might be better to have it above the table cuz i feel like it looks kinda awks in between but lol just a suggestion

**Comment by Tahmeed27** [comment]
> LGTM - just 1 question: I don't think this was in the design that was linked on the notion ticket so might be out of scope for this ticket but @Tahmeed27 do you know if this is how we wanted to present the tags? image thinking it might be better to have it above the table cuz i feel like it looks kinda awks in between but lol just a suggestion

Omg that's a good catch I'll run it by the designers and see what they think

**Comment by hyunzeekim** [comment]
> LGTM - just 1 question: I don't think this was in the design that was linked on the notion ticket so might be out of scope for this ticket but @Tahmeed27 do you know if this is how we wanted to present the tags? image thinking it might be better to have it above the table cuz i feel like it looks kinda awks in between but lol just a suggestion

Fixed!! Let me know if that looks better @chriistine

**Pull request merged**
