### PR TITLE
[Bug] Published Status is Incorrect

### PR DESCRIPTION
**Pull request by williamtran10**
## Notion ticket link

[Published Status is Incorrect](https://www.notion.so/uwblueprintexecs/Published-Status-is-Incorrect-e4a4f9de7f214df28db4721f07c04b8d)

## Implementation description
* gets publishedAt value dynamically

## Steps to test
1. while creating review, hit previous before you save or submit
2. verify it says draft in top-left of modal

## Checklist
- [x] My PR name is descriptive and in imperative tense
- [x] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [x] I have run the appropriate linter(s)
- [x] I have run docker-compose up and my project compiled
- [x] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

### CODE REVIEW

**Review by susheelk — CHANGES_REQUESTED** [review]
This seems to cause all reviews to preview as "draft" in the edit page. This review is published but it still says draft
image

**Comment by williamtran10** [comment]
Now grabs the publishedAt value dynamically for that modal

**Review by susheelk — CHANGES_REQUESTED** [review]
image
It's still happening :cry:

**Comment by williamtran10** [comment]
Screen Shot 2022-08-10 at 9 30 06 PM
is it possible the FE wasn't updated in the link when you tried? i cant recreate that screenshot right now

**Comment by susheelk** [comment]
> Screen Shot 2022-08-10 at 9 30 06 PM
> is it possible the FE wasn't updated in the link when you tried? i cant recreate that screenshot right now

This was totally mb, it worked after an empty cache + hard reload :facepalm:

**Review by susheelk — APPROVED** [review]
LGTM! :slightly_smiling_face:

**Pull request merged**
